#!/bin/bash
# Reproducible install of the SEER vLLM fork.
#
# Clones vllm-project/vllm at v0.8.5.post1, applies the eviction-order
# hook patch (0001-add-eviction-order-hook.patch), and symlinks the
# compiled .so artifacts from the conda environment's site-packages
# install so the fork is usable via PYTHONPATH override without a full
# CUDA build.
#
# Usage:
#   bash seer/integration/vllm_patches/install_fork.sh \
#       /path/to/vllm-seer-fork \
#       /path/to/conda/env/lib/python3.11/site-packages
set -e

FORK_DIR=${1:-/home/lzq/codes/vllm-seer-fork}
SITE_DIR=${2:-/home/lzq/miniconda3/envs/seer/lib/python3.11/site-packages}
PATCH=$(cd "$(dirname "$0")" && pwd)/0001-add-eviction-order-hook.patch

if [ ! -d "${FORK_DIR}" ]; then
    git clone --depth 1 --branch v0.8.5.post1 \
        https://github.com/vllm-project/vllm.git "${FORK_DIR}"
fi

cd "${FORK_DIR}"
if ! git rev-parse --verify seer-eviction-hook >/dev/null 2>&1; then
    git config user.email "seer@local" 2>/dev/null || true
    git config user.name "SEER" 2>/dev/null || true
    git checkout -b seer-eviction-hook
    git am "${PATCH}"
fi

# Stub the version module that the wheel build normally generates.
if [ ! -f "${FORK_DIR}/vllm/_version.py" ]; then
    cat > "${FORK_DIR}/vllm/_version.py" <<EOF
__version__ = "0.8.5.post1+seer.eviction"
__version_tuple__ = (0, 8, 5, "post1", "seer.eviction")
EOF
fi

# Symlink the compiled .so artifacts from site-packages into the fork.
SITE=${SITE_DIR}/vllm
ln -sf ${SITE}/_C.abi3.so ${FORK_DIR}/vllm/_C.abi3.so
ln -sf ${SITE}/_moe_C.abi3.so ${FORK_DIR}/vllm/_moe_C.abi3.so
ln -sf ${SITE}/_flashmla_C.abi3.so ${FORK_DIR}/vllm/_flashmla_C.abi3.so
ln -sf ${SITE}/cumem_allocator.abi3.so ${FORK_DIR}/vllm/cumem_allocator.abi3.so
ln -sf ${SITE}/vllm_flash_attn/_vllm_fa2_C.abi3.so \
       ${FORK_DIR}/vllm/vllm_flash_attn/_vllm_fa2_C.abi3.so
ln -sf ${SITE}/vllm_flash_attn/_vllm_fa3_C.abi3.so \
       ${FORK_DIR}/vllm/vllm_flash_attn/_vllm_fa3_C.abi3.so
# Symlink missing Python files in vllm_flash_attn (auto-generated by
# wheel install but not in the upstream source tree).
ln -sf ${SITE}/vllm_flash_attn/__init__.py \
       ${FORK_DIR}/vllm/vllm_flash_attn/__init__.py
ln -sf ${SITE}/vllm_flash_attn/flash_attn_interface.py \
       ${FORK_DIR}/vllm/vllm_flash_attn/flash_attn_interface.py
ln -sf ${SITE}/vllm_flash_attn/layers \
       ${FORK_DIR}/vllm/vllm_flash_attn/layers
ln -sf ${SITE}/vllm_flash_attn/ops \
       ${FORK_DIR}/vllm/vllm_flash_attn/ops

echo "Fork installed at ${FORK_DIR}"
echo "Use:"
echo "  PYTHONPATH=${FORK_DIR}:\$PYTHONPATH python ..."
